# 16.10.2018-a
#
###  LED Band K端che oben - ON at Sunset
- alias: LED K端che ON
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    - service: light.turn_on
      entity_id: light.steckdose_wohzimmer
#
###  LED Band K端che oben - OFF at 22:00
- alias: LED K端che OFF
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: light.turn_off
      entity_id: light.steckdose_wohzimmer
