### Uptimerobot.com - paused to to DNS request flooding ###
# - platform: uptimerobot
#     api_key: !secret uptimerobot_api

### Workday sensor - https://www.home-assistant.io/components/binary_sensor.workday/
- platform: workday
  country: DE
  province: NW
