homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml

automation: !include automations.yaml
binary_sensor: !include binarysensor.yaml
# cloud:
config:
conversation:
#device_tracker: !include devicetracker.yaml
discovery:
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token
frontend:
group: !include groups.yaml
history:
# introduction:
logbook:
luftdaten:
  sensor_id: 22160
  show_on_map: false
  sensors:
    monitored_conditions:
      - P1
      - P2
map:
#notify: !include notify.yaml
recorder:
  purge_keep_days: 5
  purge_interval: 1
script: !include scripts.yaml
sensor: !include sensor.yaml
sun:
#switch: !include switch.yaml
system_health:
tts:
  - platform: google
updater:
  include_used_components: true
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
