### Google Travel Time ###
- platform: google_travel_time
  api_key: !secret google_traffic_api
  name: Fahrzeit SU-Home
  origin: !secret ort_kal
  destination: !secret ort_heimat

- platform: google_travel_time
  api_key: !secret google_traffic_api
  name: Fahrzeit Home-SU
  origin: !secret ort_heimat
  destination: !secret ort_kal
  
### Luftdaten ###
- platform: luftdaten
  sensorid: 6580
  name: Wolsdorf
  monitored_conditions:
    - P1
    - P2
    
- platform: luftdaten
  sensorid: 6581
  monitored_conditions:
    - temperature
    - humidity

### piHole openVPN Pi2 ###
- platform: pi_hole
  host: !secret ip_pi2holeVPN
  name: pi2hole-OpenVPN
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_clients
    - unique_domains
    - clients_ever_seen
    
### Tankerkönig E10 Kraftstoffpreise  Query every 900+ seconds ###
- platform: rest
  resource: https://creativecommons.tankerkoenig.de/json/prices.php?apikey=xxxx&ids=2025cec6-d76f-422b-b305-fe6b75be12e9
  name: Mundorf E10
  unit_of_measurement: '€'
  value_template: '{{ value_json.prices["2025cec6-d76f-422b-b305-fe6b75be12e9"].e10 }}'
  scan_interval: 901
  
- platform: rest
  resource: https://creativecommons.tankerkoenig.de/json/prices.php?apikey=xxxx&ids=005056ba-7cb6-1ed2-bceb-87412ca64d30
  name: Zeithstr E10
  unit_of_measurement: '€'
  value_template: '{{ value_json.prices["005056ba-7cb6-1ed2-bceb-87412ca64d30"].e10 }}'
  scan_interval: 902
  
- platform: rest
  resource: https://creativecommons.tankerkoenig.de/json/prices.php?apikey=xxxx&ids=5e665e1a-1512-49ab-822f-1e8d7cd51e93
  name: Agip Neustadt E10
  unit_of_measurement: '€'
  value_template: '{{ value_json.prices["5e665e1a-1512-49ab-822f-1e8d7cd51e93"].e10 }}'
  scan_interval: 903

### Systemmonitor ###
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: last_boot
    - type: since_last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use

### Uptime Home-Assistant ###
- platform: uptime
  name: HA Uptime
  unit_of_measurement: hours

### Weather - Darksky - Yr ###
- platform: darksky
  api_key: !secret darksky_api
  forecast: 1
  language: de
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
  update_interval:
    minutes: 5
  units: si

- platform: yr
  name: yr Wetter
#  forecast: 24
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - dewpointTemperature
    - windSpeed
    - windDirection
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    
### Waze Travel Time ###
- platform: waze_travel_time
  name: Arbeit
  origin: !secret ort_kal
  destination: !secret ort_flb
  region: 'EU'
  
### Zyxel Switch 24Port - Uptime ###
- platform: snmp
  host: !secret ip_switchzyx24p
  name: Zyxel Switch Uptime
  version: 2c
  community: hass
  accept_errors: true
  baseoid: 1.3.6.1.2.1.1.3.0
  unit_of_measurement: 'days'
  value_template: '{{((value | int) / 8640000) | round(1)}}'
